# fly.toml app configuration file generated for igknite on 2024-09-30T19:16:03+06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'igknite'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
